version: '3'

services:
  test_build_tinyproxy:
    build: .
    image: test_build_tinyproxy
    container_name: test_build_tinyproxy
    ports:
      - 8989:8989
    environment:
      - TINYPROXY_PORT=8989
      - TINYPROXY_BIND=127.0.0.1
      - TINYPROXY_ALLOW_1=192.168.0.0/16
      - TINYPROXY_ALLOW_2=172.16.0.0/12
      - TINYPROXY_ALLOW_3=10.0.0.0/8
      - TINYPROXY_BASICAUTH=foo bar
